 name: Deploy the backend
 on:
   push:
     branches:
       - main
 jobs:
   build:
     runs-on: ubuntu-latest
     steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Docker Login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Docker Build and Push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./docker/Dockerfile.backend
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/monorepo-backend:${{ github.sha }}

    # steps to deploy to a vm
      - name: Set up SSH 
        run: |
             echo "${{ secrets.GCP_SSH_KEY }}" > private_key.pem
             chmod 600 private_key.pem

      - name: Deploy to Production vm
        run: |
          ssh -o StrictHostKeyChecking=no -i private_key.pem ${{ secrets.GCP_USER }}@${{ secrets.GCP_HOST}} << 'EOF'
          sudo docker run -d -p 8080:8080 sahilansarimondal/monorepo-backend:${{ github.sha }}
             

     