 name: Deploy the websoket
 on:
   push:
     branches:
       - main
 jobs:
   build:
     runs-on: ubuntu-latest
     steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Docker Login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Docker Build and Push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./docker/Dockerfile.ws
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/monorepo-websoket:${{ github.sha }}

    # steps to deploy to a vm
     