 name: Deploy the websoket
 on:
   push:
     branches:
       - main
 jobs:
   build:
     runs-on: ubuntu-latest
     steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Docker Login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Docker Build and Push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./docker/Dockerfile.ws
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/monorepo-websoket:${{ github.sha }}

    # steps to deploy to a vm
      - name: Set up SSH
        run: |
          echo "${{ secrets.GCP_SSH_KEY }}" > private_key.pem
          chmod 600 private_key.pem

      - name: Deploy to Production vm
        run: |
          ssh -o StrictHostKeyChecking=no -i private_key.pem ${{ secrets.GCP_USER }}@${{ secrets.GCP_HOST }} << 'EOF'
            docker stop monorepo-websoket || true
            docker rm monorepo-websoket || true
            docker run -d --name monorepo-websoket -p 8081:8081 ${{ secrets.DOCKERHUB_USERNAME }}/monorepo-websoket:${{ github.sha }}
          EOF
     